class TeamFinder

  def team_return(department)
    assignments[department]
  end

  def assignments
    {
      "HMRC business" => "Team 1",
      "BIS" => "Team 1",
      "CC" => "Team 1",
      "CH" => "Team 1",
      "OME" => "Team 1",
      "DVSA business" => "Team 1",
      "DFT business" => "Team 1",
      "RPA" => "Team 1",
      "DEFRA" => "Team 1",
      "DECC" => "Team 1",
      "EA" => "Team 1",
      "UKTI" => "Team 1",
      "CMA" => "Team 1",
      "IPO" => "Team 1",
      "UKEF" => "Team 1",
      "MOD" => "Team 1",
      "SPVA" => "Team 1",
      "HMRC personal" => "Team 2",
      "Insolvency Service" => "Team 2",
      "DWP benefits" => "Team 2",
      "DFE" => "Team 2",
      "Ofsted" => "Team 2",
      "EFA" => "Team 2",
      "SFA" => "Team 2",
      "SLA" => "Team 2",
      "LR" => "Team 2",
      "VOA" => "Team 2",
      "DCLG" => "Team 2",
      "DWP disability" => "Team 2",
      "DFT disability" => "Team 2",
      "FCO" => "Team 2",
      "HO births and deaths" => "Team 2",
      "GRO" => "Team 2",
      "DFID" => "Team 2",
      "DCMS" => "Team 2",
      "UKVI" => "Red Team",
      "HO immigration" => "Red Team",
      "DVLA" => "Red Team",
      "DVSA" => "Red Team",
      "HE" => "Red Team",
      "MHRA" => "Red Team",
      "DH" => "Red Team",
      "PHE" => "Red Team",
      "YJB" => "Red Team",
      "HMCTS" => "Red Team",
      "MOJ" => "Red Team",
      "AGO" => "Red Team",
      "HO crime and security" => "Red Team",
      "Scotland" => "Red Team",
      "Wales" => "Red Team",
      "Northern Ireland" => "Red Team",
      "ONS" => "Red Team",
      "ESIF" => "Red Team",
      "OME" => "Team 4",
      "HMRC pensions" => "Team 4",
      "BIS jobs" => "Team 4",
      "DWP pensions" => "Team 4",
      "CO" => "Team 4",
      "HO citizenship" => "Team 4",
      "G Cloud" => "Team 4",
      "CESG" => "Team 4",
      "GCHQ" => "Team 4",
      "GDS" => "Team 4",
      "FCO abroad" => "Team 4",
      "HO passports" => "Team 4",
      "HMPO" => "Team 4",
      "DWP abroad" => "Team 4",
      "HMT" => "Team 4",
      "Number 10" => "Team 4",
      "Deputy PM" => "Team 4",
      "GEO" => "Team 4"
    }
  end

end
